<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\HomeController.cs" />
    <Compile Remove="Program_Reg.cs" />
    <Compile Remove="Reg.cs" />
    <Compile Remove="Views\HomeController.cs" />
    <Compile Remove="Views\Reg.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="wwwroot\assets\calendario.html.__projection.g.css" />
    <Content Remove="wwwroot\assets\calendario.html.__projection.g.js" />
    <Content Remove="wwwroot\assets\catalogo.html.__projection.g.css" />
    <Content Remove="wwwroot\assets\catalogo.html.__projection.g.js" />
    <Content Remove="wwwroot\assets\css\styles.css" />
    <Content Remove="wwwroot\assets\educativo.html.__projection.g.css" />
    <Content Remove="wwwroot\assets\educativo.html.__projection.g.js" />
    <Content Remove="wwwroot\assets\guiaturistico.html.__projection.g.css" />
    <Content Remove="wwwroot\assets\img\OIP.webp" />
    <Content Remove="wwwroot\assets\img\ui1.jpg" />
    <Content Remove="wwwroot\assets\img\ui2.jpg" />
    <Content Remove="wwwroot\assets\img\ui3.jpg" />
    <Content Remove="wwwroot\assets\img\ui4.jpg" />
    <Content Remove="wwwroot\assets\img\ui5.jpg" />
    <Content Remove="wwwroot\assets\img\ui6.jpg" />
    <Content Remove="wwwroot\assets\img\ui7.jpg" />
    <Content Remove="wwwroot\assets\img\ui8.jpg" />
    <Content Remove="wwwroot\assets\index.html.__projection.g.css" />
    <Content Remove="wwwroot\assets\index.html.__projection.g.js" />
    <Content Remove="wwwroot\assets\login.html.__projection.g.css" />
    <Content Remove="wwwroot\assets\login.html.__projection.g.js" />
    <Content Remove="wwwroot\assets\mapa.html.__projection.g.css" />
    <Content Remove="wwwroot\assets\mapa.html.__projection.g.js" />
    <Content Remove="wwwroot\assets\perfil.html.__projection.g.css" />
    <Content Remove="wwwroot\assets\perfil.html.__projection.g.js" />
    <Content Remove="wwwroot\assets\reservar.html.__projection.g.css" />
    <Content Remove="wwwroot\assets\reservar.html.__projection.g.js" />
    <Content Remove="wwwroot\assets\reservas.html.__projection.g.css" />
    <Content Remove="wwwroot\assets\reservas.html.__projection.g.js" />
    <Content Remove="wwwroot\calendario.html.__projection.g.css" />
    <Content Remove="wwwroot\calendario.html.__projection.g.js" />
    <Content Remove="wwwroot\catalogo.html.__projection.g.css" />
    <Content Remove="wwwroot\catalogo.html.__projection.g.js" />
    <Content Remove="wwwroot\reservar.html.__projection.g.css" />
    <Content Remove="wwwroot\reservar.html.__projection.g.js" />
    <Content Remove="wwwroot\reservas.html.__projection.g.css" />
    <Content Remove="wwwroot\reservas.html.__projection.g.js" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="assets\reservas.html.__projection.g.css" />
    <None Remove="assets\reservas.html.__projection.g.js" />
    <None Remove="catalogo.html.__projection.g.css" />
    <None Remove="catalogo.html.__projection.g.js" />
    <None Remove="educativo.html.__projection.g.css" />
    <None Remove="educativo.html.__projection.g.js" />
    <None Remove="guiaturistico.html.__projection.g.css" />
    <None Remove="guiaturistico.html.__projection.g.js" />
    <None Remove="Home\login.html.__projection.g.css" />
    <None Remove="Home\login.html.__projection.g.js" />
    <None Remove="index.html.__projection.g.css" />
    <None Remove="index.html.__projection.g.js" />
    <None Remove="login.html.__projection.g.css" />
    <None Remove="login.html.__projection.g.js" />
    <None Remove="mapa.html.__projection.g.css" />
    <None Remove="mapa.html.__projection.g.js" />
    <None Remove="perfil.html.__projection.g.css" />
    <None Remove="perfil.html.__projection.g.js" />
    <None Remove="reservar.html.__projection.g.css" />
    <None Remove="reservar.html.__projection.g.js" />
    <None Remove="reservas.html.__projection.g.css" />
    <None Remove="reservas.html.__projection.g.js" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\assets\css\styles.css" />
    <None Include="wwwroot\assets\img\logo.png" />
    <None Include="wwwroot\assets\img\OIP.webp" />
    <None Include="wwwroot\assets\img\ui1.jpg" />
    <None Include="wwwroot\assets\img\ui10.jpg" />
    <None Include="wwwroot\assets\img\ui2.jpg" />
    <None Include="wwwroot\assets\img\ui3.jpg" />
    <None Include="wwwroot\assets\img\ui4.jpg" />
    <None Include="wwwroot\assets\img\ui5.jpg" />
    <None Include="wwwroot\assets\img\ui6.jpg" />
    <None Include="wwwroot\assets\img\ui7.jpg" />
    <None Include="wwwroot\assets\img\ui8.jpg" />
    <None Include="wwwroot\calendario.html" />
    <None Include="wwwroot\catalogo.html" />
    <None Include="wwwroot\educativo.html" />
    <None Include="wwwroot\guiaturistico.html" />
    <None Include="wwwroot\index.html" />
    <None Include="wwwroot\login.html" />
    <None Include="wwwroot\mapa.html" />
    <None Include="wwwroot\perfil.html" />
    <None Include="wwwroot\reservar.html" />
    <None Include="wwwroot\reservas.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="assets\css\" />
    <Folder Include="assets\img\" />
  </ItemGroup>

</Project>
